export const enum FishBoneTypes {
  EQUIPMENT = 'EQUIPMENT',
  PEOPLE = 'PEOPLE',
  PROCESS = 'PROCESS',
  MATERIALS = 'MATERIALS',
  ENVIRONMENT = 'ENVIRONMENT',
  MANAGEMENT = 'MANAGEMENT',
  MAINTENANCE = 'MAINTENANCE',
  INSPECTION = 'INSPECTION'
}
