export interface IRoles {
  id?: number;
  raiseNonconformace?: boolean;
  viewNonconformance?: boolean;
  editNonconformance?: boolean;
  viewNonconformanceTasks?: boolean;
  editNonconformanceTasks?: boolean;
  deleteNonconformanceTasks?: boolean;
  deleteNonconformance?: boolean;
  raiseChangeRequest?: boolean;
  viewCostAnalyses?: boolean;
  editCostAnalyses?: boolean;
  viewRequestSubmited?: boolean;
  editRequestSubmited?: boolean;
  approveRequestSubmited?: boolean;
  viewPendingSubmited?: boolean;
  editPendingSubmited?: boolean;
  approvePendingSubmited?: boolean;
  viewRejected?: boolean;
  editRejected?: boolean;
  editPurchaseRequest?: boolean;
  deletePurchaseRequest?: boolean;
  editProductStock?: boolean;
  addProduct?: boolean;
  deleteProduct?: boolean;
  editProduct?: boolean;
  addCustomer?: boolean;
  deleteCustomer?: boolean;
  editCustomer?: boolean;
  addSupplier?: boolean;
  deleteSupplier?: boolean;
  editSupplier?: boolean;
  raiseTask?: boolean;
  addProgressTrack?: boolean;
  deleteProgressTrack?: boolean;
  editProgressTrack?: boolean;
  viewProgressTrack?: boolean;
  addNonConformanceReason?: boolean;
  addRootCauses?: boolean;
}

export const defaultValue: Readonly<IRoles> = {
  raiseNonconformace: false,
  viewNonconformance: false,
  editNonconformance: false,
  viewNonconformanceTasks: false,
  editNonconformanceTasks: false,
  deleteNonconformanceTasks: false,
  deleteNonconformance: false,
  raiseChangeRequest: false,
  viewCostAnalyses: false,
  editCostAnalyses: false,
  viewRequestSubmited: false,
  editRequestSubmited: false,
  approveRequestSubmited: false,
  viewPendingSubmited: false,
  editPendingSubmited: false,
  approvePendingSubmited: false,
  viewRejected: false,
  editRejected: false,
  editPurchaseRequest: false,
  deletePurchaseRequest: false,
  editProductStock: false,
  addProduct: false,
  deleteProduct: false,
  editProduct: false,
  addCustomer: false,
  deleteCustomer: false,
  editCustomer: false,
  addSupplier: false,
  deleteSupplier: false,
  editSupplier: false,
  raiseTask: false,
  addProgressTrack: false,
  deleteProgressTrack: false,
  editProgressTrack: false,
  viewProgressTrack: false,
  addNonConformanceReason: false,
  addRootCauses: false
};
