export const enum AmendmentStatus {
  CHANGE_REQUEST_SUBMITED = 'CHANGE_REQUEST_SUBMITED',
  ANALYSE_CHANGE_REQUEST = 'ANALYSE_CHANGE_REQUEST',
  PLAN_CHANGE = 'PLAN_CHANGE',
  IMPLEMENT_CHANGE = 'IMPLEMENT_CHANGE',
  REVIEW_CLOSE_CHANGE = 'REVIEW_CLOSE_CHANGE'
}
