export const enum AuditNonconformaceSecondType {
  MINOR_NON_CONFORMACE = 'MINOR_NON_CONFORMACE',
  OPORTUNITY_FORIMPROVEMENT = 'OPORTUNITY_FORIMPROVEMENT',
  MAJOR_NON_CONFORMACE = 'MAJOR_NON_CONFORMACE'
}
