export const enum NotificationType {
  INVITATION = 'INVITATION',
  NEW_EMPLOYEE = 'NEW_EMPLOYEE',
  COMPANY_DELETED = 'COMPANY_DELETED',
  OTHERS = 'OTHERS',
  NEW_NON_CONFORMANCE = 'NEW_NON_CONFORMANCE',
  NON_CONFORMANCE_COMPLETED = 'NON_CONFORMANCE_COMPLETED',
  WELCOME = 'WELCOME',
  NEW_TASK = 'NEW_TASK'
}
